version: '2'
services:
  web:
    build: ./node_env
    ports: 
      - 80:3000
    volumes: 
      - ./:/home/src
    command: sh /home/src/bin/enterpoint.sh
    links:
      - redis
      - mongoDB

  redis:
    image: redis:3.2.0
  
  
  mongoDB:
    image: tutum/mongodb:3.2
    volumes:
      - db_volume:/data/db
    environment:
      AUTH: 'no'
    
volumes:
  db_volume:     
